CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL CHECK (role IN ('ROLE_ADMIN', 'ROLE_DOCTOR', 'ROLE_PATIENT')),
    created_at TIMESTAMPTZ NOT NULL
);
