server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=2001
spring.jpa.hibernate.ddl-auto=update
jwt.secret=9a4f2c8d3e1b7a6f5c8d3e1b7a6f5c8d3e1b7a6f5c8d3e1b7a6f5c8d3e1b7a6f