CREATE TABLE hospitals (id UUID PRIMARY KEY, name VARCHAR(255) NOT NULL, address VARCHAR(500) NOT NULL);
CREATE TABLE users (id UUID PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, full_name VARCHAR(255) NOT NULL, role VARCHAR(32) NOT NULL);
CREATE TABLE doctors (user_id UUID PRIMARY KEY, hospital_id UUID NOT NULL, specialty VARCHAR(255) NOT NULL);
CREATE TABLE patients (user_id UUID PRIMARY KEY, date_of_birth DATE, phone_number VARCHAR(64));
